[package]
name = "prototype"
version = "0.1.0"
edition = "2021"


[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sqlx.workspace = true
futures.workspace = true
uuid.workspace = true
diff.workspace = true